"""create risk assessments table

Revision ID: 5b2b7042473b
Revises: 7ce447fa4d72
Create Date: 2026-08-22 17:01:46.994901

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b2b7042473b"
down_revision: str | Sequence[str] | None = "7ce447fa4d72"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "risk_assessments",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ais_message_id", sa.BigInteger(), nullable=False),
        sa.Column("vessel_id", sa.BigInteger(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ml_anomaly_score", sa.Float(), nullable=False),
        sa.Column("ml_anomaly_percentile", sa.Float(), nullable=False),
        sa.Column("rule_flag_count", sa.Integer(), nullable=False),
        sa.Column("rule_severity", sa.String(length=16), nullable=False),
        sa.Column("detector_agreement", sa.Boolean(), nullable=False),
        sa.Column("risk_level", sa.String(length=16), nullable=False),
        sa.Column("risk_reasons", sa.Text(), nullable=False),
        sa.Column("assessment_version", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "risk_level IN ('low', 'medium', 'high', 'critical')",
            name=op.f("ck_risk_assessments_ck_risk_assessments_risk_level"),
        ),
        sa.CheckConstraint(
            "rule_severity IN ('none', 'warning', 'high', 'critical')",
            name=op.f("ck_risk_assessments_ck_risk_assessments_rule_severity"),
        ),
        sa.CheckConstraint(
            "ml_anomaly_percentile >= 0.0 AND ml_anomaly_percentile <= 100.0",
            name=op.f("ck_risk_assessments_ck_risk_assessments_ml_percentile_range"),
        ),
        sa.CheckConstraint(
            "rule_flag_count >= 0",
            name=op.f(
                "ck_risk_assessments_ck_risk_assessments_rule_flag_count_nonnegative"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["ais_message_id"],
            ["ais_messages.id"],
            name=op.f("fk_risk_assessments_ais_message_id_ais_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vessel_id"],
            ["vessels.id"],
            name=op.f("fk_risk_assessments_vessel_id_vessels"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_assessments")),
        sa.UniqueConstraint(
            "ais_message_id", name="uq_risk_assessments_ais_message_id"
        ),
    )
    op.create_index(
        "ix_risk_assessments_risk_level_observed_at",
        "risk_assessments",
        ["risk_level", "observed_at"],
        unique=False,
    )
    op.create_index(
        "ix_risk_assessments_vessel_observed_at",
        "risk_assessments",
        ["vessel_id", "observed_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_risk_assessments_vessel_observed_at", table_name="risk_assessments"
    )
    op.drop_index(
        "ix_risk_assessments_risk_level_observed_at", table_name="risk_assessments"
    )
    op.drop_table("risk_assessments")
    # ### end Alembic commands ###
