"""add risk assessments

Revision ID: 7ce447fa4d72
Revises: b8e72e565f0f
Create Date: 2026-08-22 16:37:16.082439

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "7ce447fa4d72"
down_revision: str | Sequence[str] | None = "b8e72e565f0f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
