"""create collision encounters table

Revision ID: 7ecc618b4b96
Revises: 5b2b7042473b
Create Date: 2026-08-23 15:11:35.200641

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ecc618b4b96"
down_revision: str | Sequence[str] | None = "5b2b7042473b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collision_encounters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vessel_a_id", sa.BigInteger(), nullable=False),
        sa.Column("vessel_b_id", sa.BigInteger(), nullable=False),
        sa.Column("vessel_a_ais_message_id", sa.BigInteger(), nullable=False),
        sa.Column("vessel_b_ais_message_id", sa.BigInteger(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("vessel_a_observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("vessel_b_observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current_distance_nm", sa.Float(), nullable=False),
        sa.Column("cpa_distance_nm", sa.Float(), nullable=False),
        sa.Column("tcpa_minutes", sa.Float(), nullable=True),
        sa.Column("relative_speed_knots", sa.Float(), nullable=False),
        sa.Column("closing_speed_knots", sa.Float(), nullable=False),
        sa.Column("bearing_from_a_to_b_degrees", sa.Float(), nullable=False),
        sa.Column("risk_level", sa.String(length=16), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("assessment_version", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["vessel_a_ais_message_id"],
            ["ais_messages.id"],
            name=op.f("fk_collision_encounters_vessel_a_ais_message_id_ais_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vessel_a_id"],
            ["vessels.id"],
            name=op.f("fk_collision_encounters_vessel_a_id_vessels"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vessel_b_ais_message_id"],
            ["ais_messages.id"],
            name=op.f("fk_collision_encounters_vessel_b_ais_message_id_ais_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vessel_b_id"],
            ["vessels.id"],
            name=op.f("fk_collision_encounters_vessel_b_id_vessels"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collision_encounters")),
        sa.UniqueConstraint(
            "vessel_a_ais_message_id",
            "vessel_b_ais_message_id",
            "assessment_version",
            name="uq_collision_encounter_source_messages_version",
        ),
    )
    op.create_index(
        "ix_collision_encounters_risk_observed_at",
        "collision_encounters",
        ["risk_level", "observed_at"],
        unique=False,
    )
    op.create_index(
        "ix_collision_encounters_vessels_observed_at",
        "collision_encounters",
        ["vessel_a_id", "vessel_b_id", "observed_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_collision_encounters_vessels_observed_at", table_name="collision_encounters"
    )
    op.drop_index(
        "ix_collision_encounters_risk_observed_at", table_name="collision_encounters"
    )
    op.drop_table("collision_encounters")
    # ### end Alembic commands ###
