"""create maritime core tables

Revision ID: b8e72e565f0f
Revises:
Create Date: 2026-08-03 20:16:40.671677

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision: str = "b8e72e565f0f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_jobs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_file", sa.Text(), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default="pending", nullable=False
        ),
        sa.Column("rows_read", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("rows_imported", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("rows_rejected", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column(
            "duplicates_skipped", sa.BigInteger(), server_default="0", nullable=False
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_jobs")),
    )
    op.create_index(
        "ix_import_jobs_status_started_at",
        "import_jobs",
        ["status", "started_at"],
        unique=False,
    )
    op.create_table(
        "vessels",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("mmsi", sa.String(length=9), nullable=False),
        sa.Column("imo", sa.String(length=16), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("call_sign", sa.String(length=32), nullable=True),
        sa.Column("vessel_type", sa.SmallInteger(), nullable=True),
        sa.Column("length_m", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("width_m", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("draft_m", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "mmsi ~ '^[0-9]{9}$'", name=op.f("ck_vessels_mmsi_nine_digits")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vessels")),
    )
    op.create_index(op.f("ix_vessels_imo"), "vessels", ["imo"], unique=False)
    op.create_index(op.f("ix_vessels_mmsi"), "vessels", ["mmsi"], unique=True)
    op.create_index(op.f("ix_vessels_name"), "vessels", ["name"], unique=False)
    op.create_geospatial_table(
        "ais_messages",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("vessel_id", sa.BigInteger(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column(
            "position",
            Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("sog", sa.Float(), nullable=True),
        sa.Column("cog", sa.Float(), nullable=True),
        sa.Column("heading", sa.Float(), nullable=True),
        sa.Column("navigation_status", sa.SmallInteger(), nullable=True),
        sa.Column("cargo", sa.Integer(), nullable=True),
        sa.Column("transceiver_class", sa.String(length=8), nullable=True),
        sa.Column(
            "sog_unavailable", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "cog_unavailable", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "heading_unavailable", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cog IS NULL OR (cog >= 0 AND cog < 360)",
            name=op.f("ck_ais_messages_cog_range"),
        ),
        sa.CheckConstraint(
            "heading IS NULL OR (heading >= 0 AND heading < 360)",
            name=op.f("ck_ais_messages_heading_range"),
        ),
        sa.CheckConstraint(
            "latitude BETWEEN -90 AND 90", name=op.f("ck_ais_messages_latitude_range")
        ),
        sa.CheckConstraint(
            "longitude BETWEEN -180 AND 180",
            name=op.f("ck_ais_messages_longitude_range"),
        ),
        sa.CheckConstraint(
            "sog IS NULL OR sog >= 0", name=op.f("ck_ais_messages_sog_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["vessel_id"],
            ["vessels.id"],
            name=op.f("fk_ais_messages_vessel_id_vessels"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ais_messages")),
        sa.UniqueConstraint(
            "vessel_id", "timestamp", "latitude", "longitude", name="identity"
        ),
    )
    op.create_geospatial_index(
        "idx_ais_messages_position",
        "ais_messages",
        ["position"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        "ix_ais_messages_timestamp", "ais_messages", ["timestamp"], unique=False
    )
    op.create_index(
        "ix_ais_messages_vessel_timestamp",
        "ais_messages",
        ["vessel_id", "timestamp"],
        unique=False,
    )
    op.create_table(
        "anomaly_alerts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ais_message_id", sa.BigInteger(), nullable=False),
        sa.Column("vessel_id", sa.BigInteger(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("anomaly_type", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("metric_name", sa.String(length=64), nullable=False),
        sa.Column("metric_value", sa.Float(), nullable=True),
        sa.Column("threshold", sa.Float(), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ais_message_id"],
            ["ais_messages.id"],
            name=op.f("fk_anomaly_alerts_ais_message_id_ais_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vessel_id"],
            ["vessels.id"],
            name=op.f("fk_anomaly_alerts_vessel_id_vessels"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_anomaly_alerts")),
        sa.UniqueConstraint(
            "ais_message_id", "anomaly_type", name="message_anomaly_type"
        ),
    )
    op.create_index(
        "ix_anomaly_alerts_type_severity",
        "anomaly_alerts",
        ["anomaly_type", "severity"],
        unique=False,
    )
    op.create_index(
        "ix_anomaly_alerts_vessel_observed_at",
        "anomaly_alerts",
        ["vessel_id", "observed_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_anomaly_alerts_vessel_observed_at", table_name="anomaly_alerts")
    op.drop_index("ix_anomaly_alerts_type_severity", table_name="anomaly_alerts")
    op.drop_table("anomaly_alerts")
    op.drop_index("ix_ais_messages_vessel_timestamp", table_name="ais_messages")
    op.drop_index("ix_ais_messages_timestamp", table_name="ais_messages")
    op.drop_geospatial_index(
        "idx_ais_messages_position",
        table_name="ais_messages",
        postgresql_using="gist",
        column_name="position",
    )
    op.drop_geospatial_table("ais_messages")
    op.drop_index(op.f("ix_vessels_name"), table_name="vessels")
    op.drop_index(op.f("ix_vessels_mmsi"), table_name="vessels")
    op.drop_index(op.f("ix_vessels_imo"), table_name="vessels")
    op.drop_table("vessels")
    op.drop_index("ix_import_jobs_status_started_at", table_name="import_jobs")
    op.drop_table("import_jobs")
    # ### end Alembic commands ###
